# Generated by Django 4.2.30 on 2026-05-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_thumbnail_url_alter_lesson_video_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(choices=[('web_dev', 'Web Development'), ('programming', 'Programming')], default='web_dev', max_length=20),
        ),
    ]
